name: Test build
on: [pull_request]

permissions:
  contents: read

jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clean Qt directory
        run: rm -rf ${{ runner.workspace }}/Qt
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          host: 'linux'
          target: 'desktop'
          modules: 'qtcharts qtvirtualkeyboard'
      - run: mkdir build && cd build && qmake .. && make
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "build/PowertuneQMLGui"
