# GitHub Action that enables a repo to achieve gradual compliance with cpplint by
#     linting only those files that have been added or modified (vs. origin/main).
# 1. runs cpplint only on those files that have been modified vs. origin/main.
# From: https://github.com/cpplint/GitHub-Action-for-cpplint

name: cpplint_modified_files
on: [pull_request]
permissions:
  contents: read
  pull-requests: write
jobs:
  cpplint_modified_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: python -m pip install cpplint
      - name: Compute modified files
        run: |
          git diff --name-only origin/${{ github.base_ref }}...${{ github.sha }} > git_diff.txt
          echo "Modified files ($(wc -l < git_diff.txt)):"
          cat git_diff.txt
      - name: cpplint_modified_files
        run: python .github/workflows/lint.py
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "cpplint.txt"
      - uses: actions/github-script@v7
        if: steps.check_files.outputs.files_exists == 'true'
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs')
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: fs.readFileSync('cpplint.txt', 'utf8')
            })
        