name: Lint

on:
  push:
    branches: [develop]
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate QML and JavaScript files
        uses: liri-infra/qmllint-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
